apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: storage-pvc-resored
spec:
  storageClassName: storage-kub
  dataSource: 
    name: test-snapshot
    kind: VolumeSnapshot
    apiGroup: snapshot.storage.k8s.io
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
