apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-tls
  labels:
    app: nginx-tls
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-tls

  template:
    metadata:
      labels:
        app: nginx-tls
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/agent-inject-status: "update"
        vault.hashicorp.com/role: "otus"
        vault.hashicorp.com/agent-inject-secret-server.cert: "pki_int/issue/example-dot-ru"
        vault.hashicorp.com/agent-inject-template-server.cert: |
          {{- with secret "pki_int/issue/example-dot-ru" "common_name=test.example.ru" "ttl=1m" -}}
          {{ .Data.certificate }}
          {{- end }}
        vault.hashicorp.com/agent-inject-secret-server.key: "pki_int/issue/example-dot-ru"
        vault.hashicorp.com/agent-inject-template-server.key: |
          {{- with secret "pki_int/issue/example-dot-ru" "common_name=test.example.ru" "ttl=1m" -}}
          {{ .Data.private_key }}
          {{- end }}
        vault.hashicorp.com/tls-skip-verify: "true"
        vault.hashicorp.com/service: "http://vault:8200"
        vault.hashicorp.com/agent-inject-command: "nginx -s reload"

    spec:
      serviceAccountName: vault-auth
      containers:
      - name: nginx-tls
        image: olegim89/nginx:v0.2
        ports:
          - containerPort: 443
            name: https