apiVersion: v1
kind: ServiceAccount
metadata:
  name: dave

# 

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: not_access

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: not_access
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: not_access
subjects:
  - kind: ServiceAccount
    name: dave
    namespace: default