apiVersion: v1
kind: ConfigMap
metadata:
  name: vault-injector-configmap
data:
  config.hcl: |
    "auto_auth" = {
      "method" = {
        "config" = {
          "role" = "otus"
        }
        "type" = "kubernetes"
      }

      "sink" = {
        "config" = {
          "path" = "/home/vault/.token"
        }

        "type" = "file"
      }
    }

    "exit_after_auth" = false
    "pid_file" = "/home/vault/.pid"

    "template" = {
      "contents" = "{{- with secret \"database/creds/vault-role\" -}}postgres://{{ .Data.username }}:{{ .Data.password }}{{- end }}"
      "destination" = "/vault/secrets/db-creds"
    }

    "vault" = {
      "address" = "https://vault:8200"
      "ca_cert" = "/var/run/secrets/kubernetes.io/serviceaccount/ca.crt"
    }
  config-init.hcl: |
    "auto_auth" = {
      "method" = {
        "config" = {
          "role" = "otus"
        }
        "type" = "kubernetes"
      }

      "sink" = {
        "config" = {
          "path" = "/home/vault/.token"
        }

        "type" = "file"
      }
    }

    "exit_after_auth" = true
    "pid_file" = "/home/vault/.pid"

    "template" = {
      "contents" = "{{- with secret \"database/creds/vault-role\" -}}postgres://{{ .Data.username }}:{{ .Data.password }}{{- end }}"
      "destination" = "/vault/secrets/db-creds"
    }

    "vault" = {
      "address" = "https://vault:8200"
      "ca_cert" = "/var/run/secrets/kubernetes.io/serviceaccount/ca.crt"
    }
