apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: server
        image: olegim89/hipster-frontend:v.0.0.2
        readinessProbe:
            initialDelaySeconds: 10
            httpGet:
              path: "/_healthz"
              port: 8080
              httpHeaders:
              - name: "Cookie"
                value: "shop_session-id=x-readiness-probe"
        env:
          - name: PRODUCT_CATALOG_SERVICE_ADDR
            value: "localhost:2000"
          - name: CURRENCY_SERVICE_ADDR
            value: "localhost:2001"
          - name: CART_SERVICE_ADDR
            value: "localhost:2002"
          - name: RECOMMENDATION_SERVICE_ADDR
            value: "localhost:2003"
          - name: CHECKOUT_SERVICE_ADDR
            value: "localhost:2004"
          - name: SHIPPING_SERVICE_ADDR
            value: "localhost:2005"
          - name: AD_SERVICE_ADDR
            value: "localhost:2006"