apiVersion: apps/v1
kind: Deployment
metadata:
  name: paymentservice-reverse
  labels:
    app: paymentservice-reverse
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: paymentservice-reverse
  template:
    metadata:
      labels:
        app: paymentservice-reverse
    spec:
      containers:
      - name: server
        image: olegim89/hipster-paymentservice:v0.0.2